In [ ]:
import numpy as np
import pandas as pd

df= pd.read_csv("/content/sample_data/mnist_train_small.csv")

In [ ]:
df

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.sample()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
11453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.iloc[5]

6        0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.586    0
0.587    0
0.588    0
0.589    0
0.590    0
Name: 5, Length: 785, dtype: int64

In [ ]:
df.loc[3:7]    # not ingone negative value

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.head(15)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.tail(6)

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.shape

(19999, 785)

In [ ]:
df.isnull().sum()

6        0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.586    0
0.587    0
0.588    0
0.589    0
0.590    0
Length: 785, dtype: int64

In [ ]:
df.info

<bound method DataFrame.info of        6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
19994  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
19996  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
19997  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
19998  5  0    0    0    0    0    0    0    0    0  ...      0      0      0

       0.584  0.585  0.586  0.587  0.588  0.589  0.590
0          0      0      0      0      0      0      0
1          0      0      0      0      0      0      0
2          0      0      0      0      0      0      0
3          0      0      0      0      0      0      0
4          0      0      0      0      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
19994      0      0      0      0      0      0      0
19995      0      0      0      0      0      0      0
19996      0      0      0      0      0      0      0
19997      0      0      0      0      0      0      0
19998      0      0      0      0      0      0      0

[19999 rows x 785 columns]>

In [ ]:
#implace tool --> to change the dataset

In [ ]:
#series math methods

In [ ]:
#count
df.count()

6        19999
0        19999
0.1      19999
0.2      19999
0.3      19999
         ...
0.586    19999
0.587    19999
0.588    19999
0.589    19999
0.590    19999
Length: 785, dtype: int64

In [ ]:
#sum --> product
df.sum()

6        89398
0            0
0.1          0
0.2          0
0.3          0
         ...
0.586      120
0.587        0
0.588        0
0.589        0
0.590        0
Length: 785, dtype: int64

In [ ]:
df.max()

6         9
0         0
0.1       0
0.2       0
0.3       0
         ..
0.586    62
0.587     0
0.588     0
0.589     0
0.590     0
Length: 785, dtype: int64

In [ ]:
#mean ,median ,mode,std, var

In [ ]:
df.mean()

6        4.470124
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...
0.586    0.006000
0.587    0.000000
0.588    0.000000
0.589    0.000000
0.590    0.000000
Length: 785, dtype: float64

In [ ]:
print(df.median())
print(df.std())
print(df.var())

6        4.0
0        0.0
0.1      0.0
0.2      0.0
0.3      0.0
        ...
0.586    0.0
0.587    0.0
0.588    0.0
0.589    0.0
0.590    0.0
Length: 785, dtype: float64
6        2.892807
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...
0.586    0.600333
0.587    0.000000
0.588    0.000000
0.589    0.000000
0.590    0.000000
Length: 785, dtype: float64
6        8.368332
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...
0.586    0.360400
0.587    0.000000
0.588    0.000000
0.589    0.000000
0.590    0.000000
Length: 785, dtype: float64

In [ ]:
df.describe()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
count,19999.000000,19999.0,19999.0,19999.0,19999.0,19999.0,19999.0,19999.0,19999.0,19999.0,...,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.0,19999.0,19999.0,19999.0
mean,4.470124,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.215011,0.087704,0.036502,0.013651,0.032602,0.006000,0.0,0.0,0.0,0.0
std,2.892807,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.314821,3.921664,2.712527,0.950818,2.718102,0.600333,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,254.000000,253.000000,79.000000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [ ]:
df.iloc[-1]  # why use iloc? negative indexing 2 types negative and positive  ignore negative value

6        5
0        0
0.1      0
0.2      0
0.3      0
        ..
0.586    0
0.587    0
0.588    0
0.589    0
0.590    0
Name: 19998, Length: 785, dtype: int64

In [ ]:
#slicing
df[5:16]

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# negative slicing means last se start krega value

In [ ]:
df[-5:]

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#fancy indexing

df.loc[[19994,19995,19996]]

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_series = df['5']
df_series[19995]=100
df_series

0         85
1         55
2        254
3         35
4        253
        ...
19994    100
19995    100
19996    253
19997      0
19998      0
Name: 5, Length: 19999, dtype: int64

In [ ]:
df['6']=100
df

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df[0]=100
df

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,0
0,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
1,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
2,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
3,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
4,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19995,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19996,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19997,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19998,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100

In [ ]:
df.loc[6:7]=100   #slicing
df

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590,0
0,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
1,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
2,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
3,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
4,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19995,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19996,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19997,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100
19998,100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,100